version: "3.9"

services:
  admin:
    image: node:20-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ui_node_modules:/workspace/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: >
      sh -c "
        if [ ! -d node_modules ]; then npm ci; fi;
        if [ -f nx.json ]; then
          npx nx serve admin --host=0.0.0.0 --port=4200 --verbose
        else
          npx ng serve admin --host 0.0.0.0 --port 4200
        fi
      "
    expose:
      - "4200"

  landing:
    image: node:20-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ui_node_modules:/workspace/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: >
      sh -c "
        if [ ! -d node_modules ]; then npm ci; fi;
        if [ -f nx.json ]; then
          npx nx serve landing --host=0.0.0.0 --port=4201 --verbose
        else
          npx ng serve landing --host 0.0.0.0 --port 4201
        fi
      "
    expose:
      - "4201"

  backend:
    image: node:20-alpine
    working_dir: /workspace/backend
    volumes:
      - ./backend:/workspace/backend
      - backend_node_modules:/workspace/backend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm ci && npm run start:dev"
    expose:
      - "3000"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - admin
      - landing
      - backend
    ports:
      - "8080:80"  # open http://localhost:8080
    volumes:
      - ./deploy/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  ui_node_modules:
  backend_node_modules:
